### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maxanes** [raphael-group/decifer#13]
Hi, 

I am really new in the field, and I would like to ask if it is possible to run DeCiFer on WES data and if I have a single biopsy from the patient?
I mean if I have somatic M2 VCF (call from matched normal/tumor) that looks like this:
![image](https://user-images.githubusercontent.com/92018021/141749986-f89711c2-ec5c-423e-8106-7d46eb8742b7.png)

Thank you.
Marijana

**Comment by maxanes** [comment]
Hi again,
Is this still active support?

**Comment by simozacca** [comment]
Hi, thank you for your question and sorry for the delay. Yes, DeCiFer can be applied to single-sample datasets, even though we expect the power and accuracy of the approach will be lower. You can follow the default guidelines for doing this as no special change is needed.

Please feel free to re-open the issue in case of additional questions.

**Comment by maxanes** [comment]
Thank you for the reply and for the development of this great tool!
