### ISSUE TITLE
Question regrading CNAs 

### ISSUE THREAD

**Issue by maxanes** [raphael-group/decifer#15]
Hi,
I have identified CNAs with PureCN tool, and I have these two files as output:

1, normal.alignment_coverage_loess.txt.gz (from the normal sample and the same from tumor sample of the same patient) looking like below:
![image](https://user-images.githubusercontent.com/92018021/144385340-6b1c4fed-6103-4efc-b5a3-508ad9d4f88b.png)

2, dnacopy.seg which is short one line for each chr looking like below:
![image](https://user-images.githubusercontent.com/92018021/144385669-6425bd2e-ba76-4645-bf33-aedd221cab85.png)

Can you please help me with which of these two files to use and try to make that output looks like best.seg.ucn, is it the second one?

Thank you.

**Comment by simozacca** [comment]
The current version of DeCiFer requires allele-specific copy number calls; this is essential for accurate tracking the multiplicities and evolution of somatic mutations. Your data only contains total copy numbers. So the use of an allele-specific copy number caller would be required.

Please let us know if you have any further question.
