### ISSUE TITLE
The conda command of Automatic installation 

### ISSUE THREAD

**Issue by ybta2957e** [raphael-group/decifer#17]
I used the following command got the error "EnvironmentLocationNotFound: Not a conda environment: "
`conda install -n decifer decifer -y`

This one works
`conda create --name decifer decifer -y`

**Comment by brian-arnold** [comment]
Thank you for catching this and posting an issue! We've updated the documentation. The intended command in the documentation should be the `conda create` one... although in theory you can also use the `conda install` command too if you've previously created the environment (e.g. `conda create --name decifer`) and have activated it (e.g. `conda activate decifer`).
