### ISSUE TITLE
User scenario

### ISSUE THREAD

**Issue by shwong-tw** [raphael-group/decifer#2]
Dear developer,

Thank you for the contribution in addressing this question.
I would like to learn more about whether the current algorithm support multi-sample inference, as well as joint inference based on mutation and indels. Or whether there's a plan in adding these features in the future.

Thank you very much :)

**Comment by gsatas** [comment]
Hi,

The current algorithm does support multi-sample inference. In the input file, described under "Required Input Data" in the README, you should enter in one row for every mutation in each sample -- e.g., if you have 100 mutations and 3 samples, you'll have 300 rows in addition to the header rows. The samples would be specified in the "sample index" and "sample label" columns. 

You can see examples of multi-sample input files in the DeCiFer data repository here: https://github.com/raphael-group/decifer-data/tree/main/input/prostate/mutations

While we haven't tested the model using indels, the current model would be applicable to support small indels -- ones whose presence or absence is reliably detected at the individual read level. As a guideline, I'd say indels of <10bps could be safely used within the existing model. 

Incorporating larger variants may require further adjustments to the model, and we will consider it for a further update.

Thank you for your interest!

**Comment by shwong-tw** [comment]
Thank you for your detailed information :)
