### ISSUE TITLE
"Skipping mutation" warning still there with new state trees file

### ISSUE THREAD

**Issue by lbresadola** [raphael-group/decifer#21]
Dear all,

thanks for creating DeCiFer!

I am having issues with the warning `"UserWarning: Skipping mutation ###: State tree file does not contain state trees for the set of copy-number states that affect mutation ###."` in the DeCiFer runs.
I created new state tree files with `generatestatetrees` for two patients I am analyzing and I re-ran DeCiFer with them. However, while for one patient I don't get the warnings anymore, for the second patient the warnings are still there, although not for all SNVs for which they appeared before (168 SNVs, instead of 231).
I tried to increase `-maxCN` and `-maxXY` to extreme numbers (50), but the state tree file didn't change and this didn't solve the problem.

Do you know why this could happen? Is there any other parameter in `generatestatetrees` that should be adjusted?

The DeCiFer input files were created with `vcf2decifer.py` and these are the commands I used (both in `v2.0.2` and `v2.1.0`):
`generatestatetrees cn_states.txt > /my_path/new_state_tree_file.txt`

`decifer -p /my_input_path/decifer.purity.tsv /my_input_path/decifer.input.tsv --jobs 12 -K 15 --record --printallk --restarts 100 --statetrees /my_path/new_state_tree_file.txt --output /my_output_path/patient_XX_new_state_tree_K15`

Thanks a lot for your help!
Best,

Luisa

**Comment by brian-arnold** [comment]
Hi Luisa,
Hmmm interesting... if they aren't too large, could you post the following files here for me to peek at:
`cn_states.txt`
`/my_input_path/decifer.purity.tsv`
`/my_input_path/decifer.input.tsv`

I have a guess at what might be occurring, but it'd be best if I could do some digging on my end.
Sincerely,
Brian

**Comment by lbresadola** [comment]
Hi Brian,

thanks for your quick reply!
Here are the files (it is WES data, so they are small). I had to convert the `.tsv` files to `.txt`, since `.tsv` format is apparently not supported.

Best,

Luisa

[cn_states.txt](https://github.com/raphael-group/decifer/files/8571150/cn_states.txt)
[decifer.input.txt](https://github.com/raphael-group/decifer/files/8571213/decifer.input.txt)
[decifer.purity.txt](https://github.com/raphael-group/decifer/files/8571214/decifer.purity.txt)

**Comment by brian-arnold** [comment]
Hi Luisa,
Gryte figured out what was causing the issue. We fixed the code here on github and are in the process of making a new conda release, but until that comes out (which will hopefully be in the next day or so) you could always do a custom install of the main branch. I'll let you know as soon as I do when the new version is released!
Sincerely,
Brian

**Comment by lbresadola** [comment]
Great! Thanks a lot Brian and Gryte!

**Comment by brian-arnold** [comment]
FYI the new version should now be available.
