### ISSUE TITLE
create input issue

### ISSUE THREAD

**Issue by mkinnaman** [raphael-group/decifer#3]
Hi,

I am having trouble with the create_input.ipynb - I am getting a json formatting error when trying to open in jupyter.

I ran the code through a validator and got the following errors:
`The JSON input is NOT valid according to RFC 4627 (JSON specification). Unexpected token \t")\n" at position 3706.

Close
The JSON input is NOT valid in JavaScript, illegal character: \ (At line #98), (At position #45)`

THanks,
Michael

**Comment by simozacca** [comment]
Thank you for this catch!
@brian-arnold could please check what is going wrong? It might be related to the new version?

Also, @brian-arnold it seems that the script does not load in the [github page](create_input.ipynb), could you please try to re-create and push it after you have run it completely?

**Comment by brian-arnold** [comment]
Hi @mkinnaman, apologies for the bug. The notebook has been updated and worked on my end, but please let us know if you're still encountering problems. Thanks!

**Comment by mkinnaman** [comment]
@brian-arnold no worries! 

Would you be able to put example input files for the script in this repository? I am importing data from other callers and I am having trouble running the script on my data as it doesn't look like I have it formatted correctly. 

Thanks!
