### ISSUE TITLE
generatestatetree usage

### ISSUE THREAD

**Issue by Subhayan18** [raphael-group/decifer#30]
Hello,

I am struggling using generatestatetree function. Could you please explain how to call it (unless compiling from decifer/build/lib/decifer/cpp/generatestatetreesmain.cpp) ?

**Comment by gsatas** [comment]
Hi Subhayan,

You can find brief instructions for using generatestatetrees in the ["Addressing the "Skipping mutation warning" section" here](https://github.com/raphael-group/decifer/tree/main/scripts#adressing-the-skipping-mutation-warning). This should work directly from the conda build (I just tested it). Please let me know if you have any further questions or run into any errors. 

Gryte

**Comment by Subhayan18** [comment]
Hi Gryte,

Thank you for your fast response.
So I suppose one can call the function in the activated conda environment? something akin to:

(/home/user/DeCiFer/decifer) ***@***.*** ~]$ generatestatetrees CNA.tsv

Unfortunately I am getting missing prompt:
bash: generatestatetrees: command not found...
 
Sorry, if I missing something very obvious.

Best,
Subhayan

________________________________________

**Comment by gsatas** [comment]
Can bash find decifer itself in your environment? That is, if you run `which decifer`, is the executable found?

**Comment by Subhayan18** [comment]
Yes, it is in the environment and I can execute decifer with my own data

$which decifer
~/DeCiFer/decifer/bin/decifer

problem arises only when I want to invoke generatestatestree.

ps I followed the conda installation guide in the decifer manual.

Best,
Subhayan

________________________________________

**Comment by gsatas** [comment]
Did you follow the automatic or manual conda installation instructions? That is, did you run:

```
conda create -n decifer decifer -y -c bioconda
conda activate decifer
```

or did you run

```
git clone https://github.com/raphael-group/decifer.git && cd decifer/
conda create -c anaconda -c conda-forge -n decifer python=2.7 numpy scipy matplotlib-base pandas seaborn -y
pip install .
```

Based on the install location, I would guess the latter, in which case you'd have to also follow the "Installation of C++ component" instructions to run generatestatetrees. But the "automatic" installation instructions should include generatestatetrees without any further steps required. 

Note: I did just add the "-c bioconda" flag to the automatic instructions, which should help in case you were running into a "decifer package not found" error when installing with the automatic instructions

**Comment by Subhayan18** [comment]
Oh thanks!

Yes, I used a manual installation with updated Python version.
I will give the automatic version a go too. Will keep you posted.

________________________________________
