### ISSUE TITLE
State Tree Question

### ISSUE THREAD

**Issue by mkinnaman** [raphael-group/decifer#4]
Hi,

I did an initial run on 3 samples from same patient. Was curious how to interpret this state tree:

(1,0,0)->(2,0,0);(2,0,0)->(1,1,0);(1,1,0)->(1,0,0);(1,0,0)->(1,1,0);(1,1,0)->(1,1,1);(1,1,1)->(1,1,0);(1,1,0)->(3,0,0)

It appears to go from 1,0,0 to 1,1,0 which I don't think makes sense but maybe I am interpreting it wrong?

I have attached my output. This is for mutation in line 11
[decifer.output.xlsx](https://github.com/raphael-group/decifer/files/6415865/decifer.output.xlsx)

Kind Regards,
Michael

**Comment by gsatas** [comment]
Hi Michael, thank you for noticing this and providing an example of the output -- you are correct that this state tree doesn't make sense. This is a bug in how we are were writing out the state trees for this output file that I will fix immediately. 

In the meantime the optimization and the rest of the results wouldn't be affected by this -- If you want to use the existing results without rerunning the optimization, the correct state tree would include every other edge in the output, starting with the first. Thus, for the example you gave it would be:
(1,0,0)->(2,0,0); (1,1,0)->(1,0,0); (1,1,0)->(1,1,1); (1,1,0)->(3,0,0)

Thus removing "(2,0,0)->(1,1,0)", "(1,0,0)->(1,1,0)", "(1,1,1)->(1,1,0)"

Note that in the output, this affects all state trees with more than one edge.

**Comment by simozacca** [comment]
Bug has been corrected in ab084f9

Version v1.1 contains the correction and it will be release soon but until then please follow the following procedure to update your DeCiFer version while having activated your conda environment with `decifer` on it:
1. Clone this repository
2. `cd` into the repository
3. Run `pip install .`

**Comment by lthiberiol** [comment]
@gsatas , in this example you provided (`(1,0,0)->(2,0,0); (1,1,0)->(1,0,0); (1,1,0)->(1,1,1); (1,1,0)->(3,0,0)`), what are possible order and relation between events?
For example, I am assuming states `(1,0,0)->(2,0,0);` and `(1,1,0)->(1,0,0)` do not occur consecutively, but then what is the relation between both states? Do they both derive from the same `(1,1,0)` parent state? How would one assign the downstream states (i.e., `(1,1,0)->(1,1,1); (1,1,0)->(3,0,0)`) to other branches of the tree?
