### ISSUE TITLE
Generate state trees

### ISSUE THREAD

**Issue by zlin77** [raphael-group/decifer#6]
Dear developers,

Thank you for the contribution in addressing the question. 

Currently when I run the codes on my samples, the report says for some mutations the given state tree file doesn't contain corresponding copy-number states, and when I tried to click the link to the manual to create all required state trees, the link was broken. Could you please provide a way to address this?

Best,
Lin

**Comment by simozacca** [comment]
@brian-arnold has fixed the related documentation and provided a new functioning script for generating state trees specific to the input copy-number file. Please take a look at the new instructions at:

https://github.com/raphael-group/decifer#optionaldata

@brian-arnold please feel free to add any other important detail
